# Generated by Django 3.0.2 on 2020-01-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20200130_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variavel', 'verbose_name_plural': 'Variações'},
        ),
    ]
